version: '2'
services:
    airline-app:
        image: airline
        external_links:
            - airline-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/airline
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    airline-postgresql:
        extends:
            file: postgresql.yml
            service: airline-postgresql
